<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">


   <link name="base_footprint" />
    <xacro:include filename="common_properties.xacro" />
    <xacro:include filename="mobile_base.xacro" />
    <xacro:include filename="mobile_base_gazebo.xacro" />

    <xacro:include filename="camera.xacro" /> 
    <xacro:include filename="camera2.xacro" /> 
    <xacro:include filename="lidar.xacro" />
    <xacro:include filename="lidar2.xacro" /> 
    <xacro:include filename="lidar3.xacro" /> 
    <!-- <xacro:include filename="dokari.xacro" /> 
    <xacro:include filename="camera3_dokari.xacro" />

    <xacro:include filename="camera4_dokari.xacro" />
    <xacro:include filename="camera5_dokari.xacro" />
    <xacro:include filename="camera6_dokari.xacro" />
    <xacro:include filename="camera7_dokari.xacro" />
    <xacro:include filename="camera8_dokari.xacro" /> -->
    <!--<xacro:include filename="ur5.xacro" />-->
    
    <xacro:include filename="arm.xacro" />
    <xacro:include filename="arm_gazebo.xacro" />

    <joint name="mobilebasearm_joint" type="fixed">
         <parent link="base_link"/>
         <child link="arm_base_link2" />
         <origin xyz="0.2 0 ${base_height + 0.01}" rpy="0 0 ${pi / 2.0} " />
     </joint>


</robot>
